//
// AcquireAccessTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AcquireAccessTokenRequest: Codable, JSONEncodable, Hashable {

    static let usernameRule = StringRule(minLength: nil, maxLength: 256, pattern: nil)
    static let passwordRule = StringRule(minLength: nil, maxLength: 256, pattern: nil)
    public var username: String
    public var password: String

    public init(username: String, password: String) {
        self.username = username
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(password, forKey: .password)
    }
}

