//
// CreateNewAccountResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateNewAccountResponse: Codable, JSONEncodable, Hashable {

    public var access: String
    public var refresh: String
    public var account: Account

    public init(access: String, refresh: String, account: Account) {
        self.access = access
        self.refresh = refresh
        self.account = account
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case access
        case refresh
        case account
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(access, forKey: .access)
        try container.encode(refresh, forKey: .refresh)
        try container.encode(account, forKey: .account)
    }
}

