//
// ListTasksForAccountResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListTasksForAccountResponse: Codable, JSONEncodable, Hashable {

    public var next: String?
    public var prev: String?
    public var count: Int
    public var results: [Task]

    public init(next: String?, prev: String?, count: Int, results: [Task]) {
        self.next = next
        self.prev = prev
        self.count = count
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case next
        case prev
        case count
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(next, forKey: .next)
        try container.encode(prev, forKey: .prev)
        try container.encode(count, forKey: .count)
        try container.encode(results, forKey: .results)
    }
}

