//
// AccountAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AccountAPI {

    /**

     - parameter createAccountRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createNewAccount(createAccountRequest: CreateAccountRequest, apiResponseQueue: DispatchQueue = GalaxyApiAPI.apiResponseQueue, completion: @escaping ((_ data: CreateNewAccountResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return createNewAccountWithRequestBuilder(createAccountRequest: createAccountRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /v1/accounts
     - BASIC:
       - type: http
       - name: jwtAuth
     - parameter createAccountRequest: (body)  
     - returns: RequestBuilder<CreateNewAccountResponse> 
     */
    open class func createNewAccountWithRequestBuilder(createAccountRequest: CreateAccountRequest) -> RequestBuilder<CreateNewAccountResponse> {
        let localVariablePath = "/v1/accounts"
        let localVariableURLString = GalaxyApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createAccountRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateNewAccountResponse>.Type = GalaxyApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
