name: GalaxyApi
targets:
  GalaxyApi:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [GalaxyApiClient]
    info:
      path: ./Info.plist
      version: 0.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
